### ISSUE TITLE
`bs.random`: Monte Carlo algorithms for random generation in distribution

### ISSUE THREAD

**Issue by VForiel** [Gunivers/Bookshelf#1]
Implement the monte-carlo algorithm in order to generate random number according to a given distribution.

> **Note**
>
> Existing related datapack:
> https://github.com/Aeldrion/Minecraft-Random

**Comment by SBtree-bit** [comment]
I'm working on this issue

- [x] Uniform distribution
- [ ] Binomial distribution
- [ ] Geometric distribution
- [ ] Poisson distribution
