### ISSUE TITLE
`bs.hitbox`: Advanced hitbox module

### ISSUE THREAD

**Issue by Leirof** [Gunivers/Bookshelf#17]
- Use the [Dispenser API](http://dispenser.gunivers.net) to get the blocs and entity models.
- Convert these models to a set of cubic coordinates [X1,Y1,Z1,X2,Y2,Z2]
	- The union of these cubes must be equal to the initial volume
- Design a function that takes in parameter a position [X,Y,Z] and, optionally, a block ID and look, using a search tee over the blocks/entities, if the coordinate is inside one of the set of cubic coordinates (i.e. inside a block/entity hitbox)   
	- If the block ID is not set, then the system will try to call the `bs.block:get` function
	- If the function is not reachable, then it fallback to a simple detection (if there is a block in the grid cell of the input parameter, it return True, even if the bloc volume doesn't fill all the grid cell volume.
	- The system will also try to detect all the nearby entities and do the same thing (volume -> set of coordinates -> detection of position being inside one of them)

**Comment by Leirof** [comment]
Créer un module hitbox contenant notamment:
- `get_entity_height`: récupère la hauteur d'une entité
- `get_entity_width`: récupère la largeur d'une entité
- `is_in_entity_ata`: détermine si la position d'execution est incluse dans la hitbox de l'entité source
- `is_in_block_ata`: détermine si l'entité source est dans la hitbox du block ciblé par la position d'execution
- `in_entities`: place un tag sur toutes les entités dont la position de l’exécution se trouve dans sa hitbox

**Comment by aksiome** [comment]
Every hitbox is now hardcoded into the view module, so this module is less needed.
But moving hitboxes into their own module could in the end be a good thing for a next refactor!
