### ISSUE TITLE
Enable modification of the log message

### ISSUE THREAD

**Issue by theogiraudet** [Gunivers/Bookshelf#170]
If a data packer creates a new library over Boohshelf, `bs.log` may be used to log messages to the user of the new library.
In this situation, the data packer should be able to modify at least the prefix of the log message to replace it by the name of their own library.
In the following screenshot, the prefix is "BS" for "Bookshelf".

![image](https://github.com/Gunivers/Bookshelf/assets/28688370/99246fa4-80e2-426d-a5ad-b6b2b9ace91e)

Proposition:
- Add a new storage `bs:config` where the data packer can overwrite some default configuration.
- Add `bs:config log.prefix.text`, `bs:config log.prefix.color`, `bs:config log.prefix.feature.color`, `bs:config log.separator.text`, `bs:config log.separator.color` and why not ways to configure the color of the severity.

**Comment by aksiome** [comment]
Alors pour le module dump j'utilise deja le storage const pour de la config (la coloration syntaxique), mais config serait effectivement plus adapté.
Pour ce qui est de la config en elle meme je pense que ca serait plus simple d'avoir juste un text component pour chaque niveau en config (comme ca on a juste à utiliser interpret et ca complexifie pas les cmds) en plus l'utilisateur peut modifier le msg comme il veut.

**Comment by theogiraudet** [comment]
Do you have an example?
But if your solution offers more customization, I'm all for it.

**Comment by aksiome** [comment]
We could have this for example:
```mcfunction
data modify storage bs:config log set value { error: '[{"text":"BS","color":"aqua"},{"text":" [ERROR]","color":"#DE382B"},{"text":" $(path)","color":"dark_aqua"},{"text":" > ","color":"gray"}]' }
```
Then in the log function we just have to run:
```mcfunction
tellraw @s [{"storage":"bs:config","nbt":"error","interpret":true}]
```

**Comment by theogiraudet** [comment]
Okay I'm fine with this.
I can contribute that.
