### ISSUE TITLE
Randomized fill function

### ISSUE THREAD

**Issue by SBtree-bit** [Gunivers/Bookshelf#219]
Imagine if there was a function, `#bs.block:fill_random`. The inputs would be the same as the `#bs.block:fill_block`, except `block` would be switched for `blocks`:

- `blocks`: Array of objects that define the blocks to fill the area with
  - `chance`: A number between 0 and 1 that defines the random chance of picking the block
  - `block`: The block that this object represents

This could help with creating “brushes” via data packs to texture buildings/procedural land.

**Comment by aksiome** [comment]
This would be great. Imo we should use `weight` instead of `chance`. It's easier to manipulate and to randomly select in a list and also it matches the random of loot_tables.
