### ISSUE TITLE
ADD `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by AugustinMauroy** [Gunivers/Bookshelf#42]
I propose to add a guideline contribution

**Comment by Leirof** [comment]
There is already one: https://bookshelf.docs.gunivers.net/projects/glib-core/en/latest/contribute/index.html

**Comment by AugustinMauroy** [comment]
Ok just in readme the link it's broke.

**Comment by Leirof** [comment]
Ah yep, the project is in an undergoing massive refactor, lot of links are temporarily broken for now ^^'

**Comment by Leirof** [comment]
Fixed ✅
