### ISSUE TITLE
Release artifacts

### ISSUE THREAD

**Issue by Leirof** [Gunivers/Bookshelf#54]
Actuellement, la release ne fait que zip de code bêtement, ce qui n'est pas très intéressant pour la lib.

Il faudrait plutôt avoir N+3 produits téléchargeable :
- [ ] Le monde dans sa globalité, soit l'ensemble du code sauf de `.gitignore`, `.github, `generator` et `docs`
- [ ] Le datapack entier (`datapacks/Bookshelf/*` zippé directement dans une archive `Bookshelf-<release>`)
- [ ] Le datapack dev entier (`datapacks/Bookshelf Dev/*` zippé directement dans une archive `Bookshelf-Dev<release>`)
- [ ] Chaque module sous la forme d'un datapack indépendant (avec et sans dépendance). Pour check les dépendances il suffit de lire le tag load de chaque module.

Level god tiers:
- [ ] Au moment de créer les modules indépendant, scanner le code afin de détecter les appels à des fichiers hors du module, de façon récursive, et ajouter ces fichiers (avec leur dossiers parents) à l'archive

**Comment by aksiome** [comment]
Done in #178 !
